/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/animated/test-robot1.gltf 
*/

import { useEffect, useMemo, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const CraneGuardLevel1=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/animated/test-robot1.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
    console.log("HELLO");
    console.log(actions);
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="group150588120" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group2070648034" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group212323912" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group348524121" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1269694942" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group2079650734" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1659004370" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group2035210330" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group430026532" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1557778044" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1531096767" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group939193378" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group955268754" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1922888928" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group528839070" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group90221255" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group467084461" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group631482178" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group303531726" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1724232230" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group975839579" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group326252368" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1950726988" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group788516393" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1943229017" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1509477332" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group101461611" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1533341509" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group305786735" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group763787916" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group582673322" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1458632382" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group105851063" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1606391483" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1152768965" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1574402815" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group180832049" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group835979637" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group200595692" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group793120268" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group11984473" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1827757204" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group162621989" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1823010756" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1479050474" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group1162203294" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group313892816" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group424423836" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="group254215753" rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="mesh101461611" geometry={nodes.mesh101461611.geometry} material={nodes.mesh101461611.material} skeleton={nodes.mesh101461611.skeleton} />
          <skinnedMesh name="mesh105851063" geometry={nodes.mesh105851063.geometry} material={nodes.mesh105851063.material} skeleton={nodes.mesh105851063.skeleton} />
          <skinnedMesh name="mesh1152768965" geometry={nodes.mesh1152768965.geometry} material={nodes.mesh1152768965.material} skeleton={nodes.mesh1152768965.skeleton} />
          <skinnedMesh name="mesh1162203294" geometry={nodes.mesh1162203294.geometry} material={nodes.mesh1162203294.material} skeleton={nodes.mesh1162203294.skeleton} />
          <skinnedMesh name="mesh11984473" geometry={nodes.mesh11984473.geometry} material={nodes.mesh11984473.material} skeleton={nodes.mesh11984473.skeleton} />
          <skinnedMesh name="mesh1269694942" geometry={nodes.mesh1269694942.geometry} material={nodes.mesh1269694942.material} skeleton={nodes.mesh1269694942.skeleton} />
          <skinnedMesh name="mesh1458632382" geometry={nodes.mesh1458632382.geometry} material={nodes.mesh1458632382.material} skeleton={nodes.mesh1458632382.skeleton} />
          <skinnedMesh name="mesh1479050474" geometry={nodes.mesh1479050474.geometry} material={nodes.mesh1479050474.material} skeleton={nodes.mesh1479050474.skeleton} />
          <skinnedMesh name="mesh150588120" geometry={nodes.mesh150588120.geometry} material={nodes.mesh150588120.material} skeleton={nodes.mesh150588120.skeleton} />
          <skinnedMesh name="mesh1509477332" geometry={nodes.mesh1509477332.geometry} material={nodes.mesh1509477332.material} skeleton={nodes.mesh1509477332.skeleton} />
          <skinnedMesh name="mesh1531096767" geometry={nodes.mesh1531096767.geometry} material={nodes.mesh1531096767.material} skeleton={nodes.mesh1531096767.skeleton} />
          <skinnedMesh name="mesh1533341509" geometry={nodes.mesh1533341509.geometry} material={nodes.mesh1533341509.material} skeleton={nodes.mesh1533341509.skeleton} />
          <skinnedMesh name="mesh1557778044" geometry={nodes.mesh1557778044.geometry} material={nodes.mesh1557778044.material} skeleton={nodes.mesh1557778044.skeleton} />
          <skinnedMesh name="mesh1574402815" geometry={nodes.mesh1574402815.geometry} material={nodes.mesh1574402815.material} skeleton={nodes.mesh1574402815.skeleton} />
          <skinnedMesh name="mesh1606391483" geometry={nodes.mesh1606391483.geometry} material={nodes.mesh1606391483.material} skeleton={nodes.mesh1606391483.skeleton} />
          <skinnedMesh name="mesh162621989" geometry={nodes.mesh162621989.geometry} material={nodes.mesh162621989.material} skeleton={nodes.mesh162621989.skeleton} />
          <skinnedMesh name="mesh1659004370" geometry={nodes.mesh1659004370.geometry} material={nodes.mesh1659004370.material} skeleton={nodes.mesh1659004370.skeleton} />
          <skinnedMesh name="mesh1724232230" geometry={nodes.mesh1724232230.geometry} material={nodes.mesh1724232230.material} skeleton={nodes.mesh1724232230.skeleton} />
          <skinnedMesh name="mesh180832049" geometry={nodes.mesh180832049.geometry} material={nodes.mesh180832049.material} skeleton={nodes.mesh180832049.skeleton} />
          <skinnedMesh name="mesh1823010756" geometry={nodes.mesh1823010756.geometry} material={nodes.mesh1823010756.material} skeleton={nodes.mesh1823010756.skeleton} />
          <skinnedMesh name="mesh1827757204" geometry={nodes.mesh1827757204.geometry} material={nodes.mesh1827757204.material} skeleton={nodes.mesh1827757204.skeleton} />
          <skinnedMesh name="mesh1922888928" geometry={nodes.mesh1922888928.geometry} material={nodes.mesh1922888928.material} skeleton={nodes.mesh1922888928.skeleton} />
          <skinnedMesh name="mesh1943229017" geometry={nodes.mesh1943229017.geometry} material={nodes.mesh1943229017.material} skeleton={nodes.mesh1943229017.skeleton} />
          <skinnedMesh name="mesh1950726988" geometry={nodes.mesh1950726988.geometry} material={nodes.mesh1950726988.material} skeleton={nodes.mesh1950726988.skeleton} />
          <skinnedMesh name="mesh200595692" geometry={nodes.mesh200595692.geometry} material={nodes.mesh200595692.material} skeleton={nodes.mesh200595692.skeleton} />
          <skinnedMesh name="mesh2035210330" geometry={nodes.mesh2035210330.geometry} material={nodes.mesh2035210330.material} skeleton={nodes.mesh2035210330.skeleton} />
          <skinnedMesh name="mesh2070648034" geometry={nodes.mesh2070648034.geometry} material={nodes.mesh2070648034.material} skeleton={nodes.mesh2070648034.skeleton} />
          <skinnedMesh name="mesh2079650734" geometry={nodes.mesh2079650734.geometry} material={nodes.mesh2079650734.material} skeleton={nodes.mesh2079650734.skeleton} />
          <skinnedMesh name="mesh212323912" geometry={nodes.mesh212323912.geometry} material={nodes.mesh212323912.material} skeleton={nodes.mesh212323912.skeleton} />
          <skinnedMesh name="mesh254215753" geometry={nodes.mesh254215753.geometry} material={nodes.mesh254215753.material} skeleton={nodes.mesh254215753.skeleton} />
          <skinnedMesh name="mesh303531726" geometry={nodes.mesh303531726.geometry} material={nodes.mesh303531726.material} skeleton={nodes.mesh303531726.skeleton} />
          <skinnedMesh name="mesh305786735" geometry={nodes.mesh305786735.geometry} material={nodes.mesh305786735.material} skeleton={nodes.mesh305786735.skeleton} />
          <skinnedMesh name="mesh313892816" geometry={nodes.mesh313892816.geometry} material={nodes.mesh313892816.material} skeleton={nodes.mesh313892816.skeleton} />
          <skinnedMesh name="mesh326252368" geometry={nodes.mesh326252368.geometry} material={nodes.mesh326252368.material} skeleton={nodes.mesh326252368.skeleton} />
          <skinnedMesh name="mesh348524121" geometry={nodes.mesh348524121.geometry} material={nodes.mesh348524121.material} skeleton={nodes.mesh348524121.skeleton} />
          <skinnedMesh name="mesh424423836" geometry={nodes.mesh424423836.geometry} material={nodes.mesh424423836.material} skeleton={nodes.mesh424423836.skeleton} />
          <skinnedMesh name="mesh430026532" geometry={nodes.mesh430026532.geometry} material={nodes.mesh430026532.material} skeleton={nodes.mesh430026532.skeleton} />
          <skinnedMesh name="mesh467084461" geometry={nodes.mesh467084461.geometry} material={nodes.mesh467084461.material} skeleton={nodes.mesh467084461.skeleton} />
          <skinnedMesh name="mesh528839070" geometry={nodes.mesh528839070.geometry} material={nodes.mesh528839070.material} skeleton={nodes.mesh528839070.skeleton} />
          <skinnedMesh name="mesh582673322" geometry={nodes.mesh582673322.geometry} material={nodes.mesh582673322.material} skeleton={nodes.mesh582673322.skeleton} />
          <skinnedMesh name="mesh631482178" geometry={nodes.mesh631482178.geometry} material={nodes.mesh631482178.material} skeleton={nodes.mesh631482178.skeleton} />
          <skinnedMesh name="mesh763787916" geometry={nodes.mesh763787916.geometry} material={nodes.mesh763787916.material} skeleton={nodes.mesh763787916.skeleton} />
          <skinnedMesh name="mesh788516393" geometry={nodes.mesh788516393.geometry} material={nodes.mesh788516393.material} skeleton={nodes.mesh788516393.skeleton} />
          <skinnedMesh name="mesh793120268" geometry={nodes.mesh793120268.geometry} material={nodes.mesh793120268.material} skeleton={nodes.mesh793120268.skeleton} />
          <skinnedMesh name="mesh835979637" geometry={nodes.mesh835979637.geometry} material={nodes.mesh835979637.material} skeleton={nodes.mesh835979637.skeleton} />
          <skinnedMesh name="mesh90221255" geometry={nodes.mesh90221255.geometry} material={nodes.mesh90221255.material} skeleton={nodes.mesh90221255.skeleton} />
          <skinnedMesh name="mesh939193378" geometry={nodes.mesh939193378.geometry} material={nodes.mesh939193378.material} skeleton={nodes.mesh939193378.skeleton} />
          <skinnedMesh name="mesh955268754" geometry={nodes.mesh955268754.geometry} material={nodes.mesh955268754.material} skeleton={nodes.mesh955268754.skeleton} />
          <skinnedMesh name="mesh975839579" geometry={nodes.mesh975839579.geometry} material={nodes.mesh975839579.material} skeleton={nodes.mesh975839579.skeleton} />
        </group>
      </group>
    </group>
  )
}

export default CraneGuardLevel1

useGLTF.preload('/animated/test-robot1.gltf')

