/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/GoodBotSit01.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function GoodBotSit03(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/GoodBotSit03.gltf');
  const { actions,names } = useAnimations(animations, group)
  useEffect(()=>{
    console.log(actions);
    console.log(names);
    // actions['Sit.001']?.reset().fadeIn(0.5).play();
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="_100Avatars_115_LaloBOT001" geometry={nodes._100Avatars_115_LaloBOT001.geometry} material={materials['_115_LaloBot.002']} skeleton={nodes._100Avatars_115_LaloBOT001.skeleton} morphTargetDictionary={nodes._100Avatars_115_LaloBOT001.morphTargetDictionary} morphTargetInfluences={nodes._100Avatars_115_LaloBOT001.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/GoodBotSit03.gltf')
